const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    description:
      "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?auto=format&fit=crop&w=800&q=60",
    },
    price: 1500,
    location: "Malibu",
    country: "United States",
    category: "Beach",
    geometry: { type: "Point", coordinates: [-118.7798, 34.0259] },
  },
  {
    title: "Modern Loft in Downtown",
    description:
      "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "New York City",
    country: "United States",
    category: "Iconic Cities",
    geometry: { type: "Point", coordinates: [-74.006, 40.7128] },
  },
  {
    title: "Mountain Retreat",
    description:
      "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=60",
    },
    price: 1000,
    location: "Aspen",
    country: "United States",
    category: "Mountains",
    geometry: { type: "Point", coordinates: [-106.82, 39.19] },
  },
  {
    title: "Historic Villa in Tuscany",
    description:
      "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=60",
    },
    price: 2500,
    location: "Florence",
    country: "Italy",
    category: "Farms",
    geometry: { type: "Point", coordinates: [11.2558, 43.7696] },
  },
  {
    title: "Secluded Treehouse Getaway",
    description:
      "Live among the treetops in this unique treehouse retreat. A true nature lover's paradise.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=60",
    },
    price: 800,
    location: "Portland",
    country: "United States",
    category: "Camping",
    geometry: { type: "Point", coordinates: [-122.6765, 45.5231] },
  },
  {
    title: "Beachfront Paradise",
    description:
      "Step out of your door onto the sandy beach. This beachfront condo offers the ultimate relaxation.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=800&q=60",
    },
    price: 2000,
    location: "Cancun",
    country: "Mexico",
    category: "Beach",
    geometry: { type: "Point", coordinates: [-86.8515, 21.1619] },
  },
  {
    title: "Rustic Cabin by the Lake",
    description:
      "Spend your days fishing and kayaking on the serene lake. This cozy cabin is perfect for outdoor enthusiasts.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=60",
    },
    price: 900,
    location: "Lake Tahoe",
    country: "United States",
    category: "Mountains",
    geometry: { type: "Point", coordinates: [-120.0324, 39.0968] },
  },
  {
    title: "Luxury Penthouse with City Views",
    description:
      "Indulge in luxury living with panoramic city views from this stunning penthouse apartment.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?auto=format&fit=crop&w=800&q=60",
    },
    price: 3500,
    location: "Los Angeles",
    country: "United States",
    category: "Trending",
    geometry: { type: "Point", coordinates: [-118.2437, 34.0522] },
  },
  {
    title: "Ski-In/Ski-Out Chalet",
    description:
      "Hit the slopes right from your doorstep in this ski-in/ski-out chalet in the Swiss Alps.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=800&q=60",
    },
    price: 3000,
    location: "Verbier",
    country: "Switzerland",
    category: "Mountains",
    geometry: { type: "Point", coordinates: [7.2266, 46.0969] },
  },
  {
    title: "Safari Lodge in the Serengeti",
    description:
      "Experience the thrill of the wild in a comfortable safari lodge. Witness the Great Migration up close.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=800&q=60",
    },
    price: 4000,
    location: "Serengeti National Park",
    country: "Tanzania",
    category: "Farms",
    geometry: { type: "Point", coordinates: [34.6857, -2.3333] },
  },
  {
    title: "Historic Canal House",
    description:
      "Stay in a piece of history in this beautifully preserved canal house in Amsterdam's iconic district.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=800&q=60",
    },
    price: 1800,
    location: "Amsterdam",
    country: "Netherlands",
    category: "Boats",
    geometry: { type: "Point", coordinates: [4.9041, 52.3676] },
  },
  {
    title: "Private Island Retreat",
    description:
      "Have an entire island to yourself for a truly exclusive and unforgettable vacation experience.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1618140052121-39fc6db33972?auto=format&fit=crop&w=800&q=60",
    },
    price: 10000,
    location: "Fiji",
    country: "Fiji",
    category: "Trending",
    geometry: { type: "Point", coordinates: [178.065, -17.7134] },
  },
  {
    title: "Charming Cottage in the Cotswolds",
    description:
      "Escape to the picturesque Cotswolds in this quaint and charming cottage with a thatched roof.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1602088113235-229c19758e9f?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Cotswolds",
    country: "United Kingdom",
    category: "Room",
    geometry: { type: "Point", coordinates: [-1.7191, 51.833] },
  },
  {
    title: "Historic Brownstone in Boston",
    description:
      "Step back in time in this elegant historic brownstone located in the heart of Boston.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1533619239233-6280475a633a?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Boston",
    country: "United States",
    category: "Iconic Cities",
    geometry: { type: "Point", coordinates: [-71.0589, 42.3601] },
  },
  {
    title: "Beachfront Bungalow in Bali",
    description:
      "Relax on the sandy shores of Bali in this beautiful beachfront bungalow with a private pool.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1602391833977-358a52198938?auto=format&fit=crop&w=800&q=60",
    },
    price: 1800,
    location: "Bali",
    country: "Indonesia",
    category: "Amazing Pools",
    geometry: { type: "Point", coordinates: [115.1889, -8.4095] },
  },
  {
    title: "Mountain View Cabin in Banff",
    description:
      "Enjoy breathtaking mountain views from this cozy cabin in the Canadian Rockies.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb?auto=format&fit=crop&w=800&q=60",
    },
    price: 1500,
    location: "Banff",
    country: "Canada",
    category: "Mountains",
    geometry: { type: "Point", coordinates: [-115.5708, 51.1784] },
  },
  {
    title: "Art Deco Apartment in Miami",
    description:
      "Step into the glamour of the 1920s in this stylish Art Deco apartment in South Beach.",
    image: {
      filename: "listingimage",
      url: "https://plus.unsplash.com/premium_photo-1670963964797-942df1804579?auto=format&fit=crop&w=800&q=60",
    },
    price: 1600,
    location: "Miami",
    country: "United States",
    category: "Iconic Cities",
    geometry: { type: "Point", coordinates: [-80.1918, 25.7617] },
  },
  {
    title: "Tropical Villa in Phuket",
    description:
      "Escape to a tropical paradise in this luxurious villa with a private infinity pool in Phuket.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1470165301023-58dab8118cc9?auto=format&fit=crop&w=800&q=60",
    },
    price: 3000,
    location: "Phuket",
    country: "Thailand",
    category: "Amazing Pools",
    geometry: { type: "Point", coordinates: [98.3984, 7.8804] },
  },
  {
    title: "Historic Castle in Scotland",
    description:
      "Live like royalty in this historic castle in the Scottish Highlands. Explore the rugged beauty of the area.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1585543805890-6051f7829f98?auto=format&fit=crop&w=800&q=60",
    },
    price: 4000,
    location: "Scottish Highlands",
    country: "United Kingdom",
    category: "Castle",
    geometry: { type: "Point", coordinates: [-4.2026, 57.1204] },
  },
  {
    title: "Desert Oasis in Dubai",
    description:
      "Experience luxury in the middle of the desert in this opulent oasis in Dubai with a private pool.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=800&q=60",
    },
    price: 5000,
    location: "Dubai",
    country: "United Arab Emirates",
    category: "Trending",
    geometry: { type: "Point", coordinates: [55.2708, 25.2048] },
  },
  {
    title: "Rustic Log Cabin in Montana",
    description:
      "Unplug and unwind in this cozy log cabin surrounded by the natural beauty of Montana.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1586375300773-8384e3e4916f?auto=format&fit=crop&w=800&q=60",
    },
    price: 1100,
    location: "Montana",
    country: "United States",
    category: "Camping",
    geometry: { type: "Point", coordinates: [-110.3626, 46.8797] },
  },
  {
    title: "Beachfront Villa in Greece",
    description:
      "Enjoy the crystal-clear waters of the Mediterranean in this beautiful beachfront villa on a Greek island.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?auto=format&fit=crop&w=800&q=60",
    },
    price: 2500,
    location: "Mykonos",
    country: "Greece",
    category: "Beach",
    geometry: { type: "Point", coordinates: [25.327, 37.4467] },
  },
  {
    title: "Eco-Friendly Treehouse Retreat",
    description:
      "Stay in an eco-friendly treehouse nestled in the forest. It's the perfect escape for nature lovers.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1488462237308-ecaa28b729d7?auto=format&fit=crop&w=800&q=60",
    },
    price: 750,
    location: "Costa Rica",
    country: "Costa Rica",
    category: "Domes",
    geometry: { type: "Point", coordinates: [-84.0907, 9.7489] },
  },
  {
    title: "Historic Cottage in Charleston",
    description:
      "Experience the charm of historic Charleston in this beautifully restored cottage with a private garden.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1587381420270-3e1a5b9e6904?auto=format&fit=crop&w=800&q=60",
    },
    price: 1600,
    location: "Charleston",
    country: "United States",
    category: "Room",
    geometry: { type: "Point", coordinates: [-79.9311, 32.7765] },
  },
  {
    title: "Modern Apartment in Tokyo",
    description:
      "Explore the vibrant city of Tokyo from this modern and centrally located apartment.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1480796927426-f609979314bd?auto=format&fit=crop&w=800&q=60",
    },
    price: 2000,
    location: "Tokyo",
    country: "Japan",
    category: "Iconic Cities",
    geometry: { type: "Point", coordinates: [139.6917, 35.6895] },
  },
  {
    title: "Lakefront Cabin in New Hampshire",
    description:
      "Spend your days by the lake in this cozy cabin in the scenic White Mountains of New Hampshire.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1578645510447-e20b4311e3ce?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "New Hampshire",
    country: "United States",
    category: "Mountains",
    geometry: { type: "Point", coordinates: [-71.5724, 43.1939] },
  },
  {
    title: "Luxury Villa in the Maldives",
    description:
      "Indulge in luxury in this overwater villa in the Maldives with stunning views of the Indian Ocean.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=800&q=60",
    },
    price: 6000,
    location: "Maldives",
    country: "Maldives",
    category: "Amazing Pools",
    geometry: { type: "Point", coordinates: [73.2207, 3.2028] },
  },
  {
    title: "Ski Chalet in Aspen",
    description:
      "Hit the slopes in style with this luxurious ski chalet in the world-famous Aspen ski resort.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=60",
    },
    price: 4000,
    location: "Aspen",
    country: "United States",
    category: "Mountains",
    geometry: { type: "Point", coordinates: [-106.82, 39.19] },
  },
  {
    title: "Secluded Beach House in Costa Rica",
    description:
      "Escape to a secluded beach house on the Pacific coast of Costa Rica. Surf, relax, and unwind.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=800&q=60",
    },
    price: 1800,
    location: "Costa Rica",
    country: "Costa Rica",
    category: "Beach",
    geometry: { type: "Point", coordinates: [-84.0907, 9.7489] },
  },
  {
    title: "Sunny Shores Villa",
    description: "A modern beachside villa with ocean views and private pool.",
    image: {
      filename: "listing1",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    },
    price: 1200,
    location: "Malibu",
    country: "USA",
    category: "Beach",
    geometry: { type: "Point", coordinates: [-118.7798, 34.0259] },
  },
  {
    title: "Himalayan Escape",
    description: "A serene mountain cabin surrounded by snowy peaks.",
    image: {
      filename: "listing2",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
    },
    price: 850,
    location: "Manali",
    country: "India",
    category: "Mountains",
    geometry: { type: "Point", coordinates: [77.1887, 32.2396] },
  },
  {
    title: "Ice Dome Retreat",
    description: "Stay inside a glass dome under the northern lights.",
    image: {
      filename: "listing3",
      url: "https://images.unsplash.com/photo-1518684079-3c830dcef090",
    },
    price: 1500,
    location: "Reykjavik",
    country: "Iceland",
    category: "Arctic",
    geometry: { type: "Point", coordinates: [-21.9426, 64.1466] },
  },
  {
    title: "Venetian Dreams",
    description: "Romantic gondola-side apartment in Venice.",
    image: {
      filename: "listing4",
      url: "https://images.unsplash.com/photo-1505761671935-60b3a7427bad",
    },
    price: 950,
    location: "Venice",
    country: "Italy",
    category: "Boats",
    geometry: { type: "Point", coordinates: [12.3155, 45.4408] },
  },
  {
    title: "Golden Desert Camp",
    description: "Luxury tents in the middle of the Thar Desert.",
    image: {
      filename: "listing5",
      url: "https://images.unsplash.com/photo-1500534623283-312aade485b7",
    },
    price: 500,
    location: "Jaisalmer",
    country: "India",
    category: "Camping",
    geometry: { type: "Point", coordinates: [70.9083, 26.9157] },
  },
  {
    title: "Emerald Dome Stay",
    description: "Eco-friendly dome accommodation surrounded by nature.",
    image: {
      filename: "listing6",
      url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    },
    price: 780,
    location: "Queenstown",
    country: "New Zealand",
    category: "Domes",
    geometry: { type: "Point", coordinates: [168.6626, -45.0312] },
  },
  {
    title: "Royal Highlands Castle",
    description: "Live like royalty in a centuries-old stone castle.",
    image: {
      filename: "listing7",
      url: "https://images.unsplash.com/photo-1500051638674-ff996a0ec29e",
    },
    price: 2000,
    location: "Edinburgh",
    country: "Scotland",
    category: "Castle",
    geometry: { type: "Point", coordinates: [-3.1883, 55.9533] },
  },
  {
    title: "Floating Haven",
    description: "Stay in a cozy houseboat surrounded by calm waters.",
    image: {
      filename: "listing8",
      url: "https://images.unsplash.com/photo-1560179707-f14e90ef3623",
    },
    price: 900,
    location: "Kerala",
    country: "India",
    category: "Boats",
    geometry: { type: "Point", coordinates: [76.2711, 9.9816] },
  },
  {
    title: "Misty Mountains Cabin",
    description: "Secluded cabin retreat with hiking trails nearby.",
    image: {
      filename: "listing9",
      url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    },
    price: 600,
    location: "Banff",
    country: "Canada",
    category: "Mountains",
    geometry: { type: "Point", coordinates: [-115.5708, 51.1784] },
  },
  {
    title: "City Luxe Apartment",
    description: "Modern apartment in the heart of New York City.",
    image: {
      filename: "listing10",
      url: "https://images.unsplash.com/photo-1486308510493-aa64833634ef",
    },
    price: 1800,
    location: "New York",
    country: "USA",
    category: "Iconic Cities",
    geometry: { type: "Point", coordinates: [-74.006, 40.7128] },
  },
  {
    title: "Coastal Comfort Home",
    description: "Beach house with open-air balcony and sea breeze.",
    image: {
      filename: "listing11",
      url: "https://images.unsplash.com/photo-1494526585095-c41746248156",
    },
    price: 1100,
    location: "Goa",
    country: "India",
    category: "Beach",
    geometry: { type: "Point", coordinates: [73.8278, 15.2993] },
  },
  {
    title: "Rainforest Farmhouse",
    description: "Rustic farmhouse amidst lush greenery and wildlife.",
    image: {
      filename: "listing12",
      url: "https://images.unsplash.com/photo-1505692794403-34d4982f4d76",
    },
    price: 700,
    location: "Amazonas",
    country: "Brazil",
    category: "Farms",
    geometry: { type: "Point", coordinates: [-60.025, -3.119] },
  },
  {
    title: "Infinity Pool Villa",
    description: "A luxury villa with an infinity pool overlooking the valley.",
    image: {
      filename: "listing13",
      url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c",
    },
    price: 2200,
    location: "Bali",
    country: "Indonesia",
    category: "Amazing Pools",
    geometry: { type: "Point", coordinates: [115.1889, -8.4095] },
  },
  {
    title: "Countryside Room Stay",
    description: "Cozy private room with vintage decor and breakfast.",
    image: {
      filename: "listing14",
      url: "https://images.unsplash.com/photo-1554995207-c18c203602cb",
    },
    price: 300,
    location: "Prague",
    country: "Czech Republic",
    category: "Room",
    geometry: { type: "Point", coordinates: [14.4378, 50.0755] },
  },
  {
    title: "Aurora Igloo Cabin",
    description: "Experience the Northern Lights from your glass cabin.",
    image: {
      filename: "listing15",
      url: "https://images.unsplash.com/photo-1541422652431-fcf7c1c54d5f",
    },
    price: 1900,
    location: "Lapland",
    country: "Finland",
    category: "Arctic",
    geometry: { type: "Point", coordinates: [25.7482, 67.8558] },
  },
  {
    title: "Forest Bubble Dome",
    description: "Transparent dome in forest clearing with night sky views.",
    image: {
      filename: "listing16",
      url: "https://images.unsplash.com/photo-1528747045269-390fe33c19d4",
    },
    price: 950,
    location: "Oregon",
    country: "USA",
    category: "Domes",
    geometry: { type: "Point", coordinates: [-122.6765, 45.5231] },
  },
  {
    title: "Farm-to-Table Cottage",
    description: "Organic farm stay offering fresh produce and calm views.",
    image: {
      filename: "listing17",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    },
    price: 650,
    location: "Tuscany",
    country: "Italy",
    category: "Farms",
    geometry: { type: "Point", coordinates: [11.2558, 43.7696] },
  },
  {
    title: "Luxury Pool Retreat",
    description: "Private villa with heated pool and modern amenities.",
    image: {
      filename: "listing18",
      url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    },
    price: 2400,
    location: "Phuket",
    country: "Thailand",
    category: "Amazing Pools",
    geometry: { type: "Point", coordinates: [98.3984, 7.8804] },
  },
  {
    title: "Nomad’s Paradise",
    description: "Remote desert stay for digital nomads seeking tranquility.",
    image: {
      filename: "listing19",
      url: "https://images.unsplash.com/photo-1519824145371-296894a0daa9",
    },
    price: 550,
    location: "Sahara",
    country: "Morocco",
    category: "Camping",
    geometry: { type: "Point", coordinates: [-7.0926, 31.7917] },
  },
  {
    title: "Skyline Penthouse",
    description: "Luxury penthouse with panoramic views of the skyline.",
    image: {
      filename: "listing20",
      url: "https://images.unsplash.com/photo-1501183638710-841dd1904471",
    },
    price: 2600,
    location: "Dubai",
    country: "UAE",
    category: "Trending",
    geometry: { type: "Point", coordinates: [55.2708, 25.2048] },
  },
  {
    title: "Costa Rica Treehouse",
    description: "Eco-treehouse stay surrounded by tropical wildlife.",
    image: {
      filename: "listing21",
      url: "https://images.unsplash.com/photo-1499696010181-32a3d0c8b2b5",
    },
    price: 1200,
    location: "Puntarenas",
    country: "Costa Rica",
    category: "Farms",
    geometry: { type: "Point", coordinates: [-84.815, 9.9797] },
  },
  {
    title: "Mountain Stream Chalet",
    description: "Charming chalet beside a crystal-clear mountain stream.",
    image: {
      filename: "listing22",
      url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    },
    price: 900,
    location: "Zermatt",
    country: "Switzerland",
    category: "Mountains",
    geometry: { type: "Point", coordinates: [7.7491, 46.0207] },
  },
  {
    title: "Ancient Castle Inn",
    description: "Sleep inside a medieval castle with modern comforts.",
    image: {
      filename: "listing23",
      url: "https://images.unsplash.com/photo-1500051638674-ff996a0ec29e",
    },
    price: 1900,
    location: "Loire Valley",
    country: "France",
    category: "Castle",
    geometry: { type: "Point", coordinates: [0.8081, 47.3499] },
  },
  {
    title: "Urban Minimalist Loft",
    description: "Chic loft apartment in a cultural downtown area.",
    image: {
      filename: "listing24",
      url: "https://images.unsplash.com/photo-1505692794403-34d4982f4d76",
    },
    price: 1750,
    location: "Tokyo",
    country: "Japan",
    category: "Iconic Cities",
    geometry: { type: "Point", coordinates: [139.6917, 35.6895] },
  },
  {
    title: "Lagoon Paradise",
    description: "Overwater bungalow with glass floor and private deck.",
    image: {
      filename: "listing25",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    },
    price: 2300,
    location: "Bora Bora",
    country: "French Polynesia",
    category: "Beach",
    geometry: { type: "Point", coordinates: [-151.7415, -16.5004] },
  },
];

module.exports = { data: sampleListings };